---
- name: Create directory for docker ecr token refresh config.
  file:
    path: "{{ aws_ecr_token_login_path }}"
    owner: root
    group: root
    state: directory
    mode: 0755

- name: Copy ecr_token.yml config file
  copy:
    src: files/ecr-config.yml
    dest: "{{ aws_ecr_token_login_config_path }}"
    owner: root
    group: root
    mode: 0644

# https://github.com/skuid/ecr-token-refresh
# docker run --restart always -d \
#-v /opt/ecr/passwords:/opt/passwords \
#-v /root/ecr-config.yml:/opt/config/ecr-token-refresh/config.yaml \
# quay.io/skuid/ecr-token-refresh:latest
- name: ecr-token-refresh container
  docker_container:
    name: ecr-token-refresh
    image: quay.io/skuid/ecr-token-refresh:latest
    state: started
    restart_policy: always
    volumes:
    - "{{ aws_ecr_token_login_path }}:/opt/passwords"
    - "{{ aws_ecr_token_login_config_path }}:/opt/config/ecr-token-refresh/config.yaml"