---
# Vault Address
_vault_address: http://127.0.0.1:8200

# Vault Token
_vault_token: ''

# Enable KV version 2
_vault_config_enable_kv_v2: true

# Enable Audit to the given file path
_vault_config_enable_audit: false
_vault_config_enable_audit_file_path: /var/log/vault_audit.log
