# ref link: https://alinex.gitlab.io/env/mkdocs/
#===================================================================================#
# Site Information
#===================================================================================#
site_name: Binbash Leverage Reference Architecture
repo_name: "binbashar/le-tf-infra-aws"
repo_url: https://github.com/binbashar/le-tf-infra-aws
site_url: https://leverage-ref-architecture.github.io/le-tf-infra-aws
site_description: Binbash Leverage Reference Architecture Documentation
site_author: Binbash
copyright: Copyright &copy; 2020 <a href="https://www.binbash.com.ar">Binbash</a>

#===================================================================================#
# Mkdocs Theme (Material Mkdocs) + Extras
#===================================================================================#
theme:
  name: material
  language: en
  icon:
      logo: material/book-open-variant
  favicon: images/logos/favicon.ico
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - tabs
    - instant
  palette:
    primary: "teal"
    accent: "green"
  include_sidebar: true

extra:
  social:
    - icon: material/github
      link: 'https://github.com/binbashar'
    - icon: material/linkedin
      link: 'https://www.linkedin.com/company/binbash'
    - icon: material/twitter
      link: 'https://twitter.com/binbash_devops'
    - icon: material/home
      link: https://www.binbash.com.ar

#===================================================================================#
# Mkdocs Markdown Extentions, Plugins & extras
#===================================================================================#
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - meta
  - toc:
      # insert a blank space before the character
      permalink: " ¶"

plugins:
  - search
  - awesome-pages

extra_css: [extra.css]

# Google Analytics
#
#google_analytics:
#  - 'UA-XXXXXXXX-X'
#  - 'auto'

#===================================================================================#
# Mkdocs Navigation Tree
#===================================================================================#
nav:
  - Welcome:
      - Welcome: "index.md"
      - How it works: "how-it-works/index.md"
      - Support: "support.md"
      - Development: "development.md"
  - How it works:
        - How it works: "how-it-works/index.md"
        - Leverage Code Library:
          - Overview: "how-it-works/code-library/code-library.md"
          - Specifications: "how-it-works/code-library/code-library-specs.md"
          - Modules per Tech: "how-it-works/code-library/modules-library-per-tech.md"
        - AWS Organization: "how-it-works/organization/organization.md"
        - Identities: "how-it-works/identities/identities.md"
        - Security:
          - VPN: "how-it-works/security/vpn.md"
          - Services: "how-it-works/security/services.md"
        - Network:
          - VPC: "how-it-works/network/vpc.md"
          - VPC Peering: "how-it-works/network/vpc-peering.md"
          - DNS: "how-it-works/network/dns.md"
        - Compute:
          - K8s Kops: "how-it-works/compute/k8s-kops.md"
          - K8s EKS: "how-it-works/compute/k8s-eks.md"
          - Serverless: "how-it-works/compute/serverless.md"
        - Database:
           - Databases: "how-it-works/database/database.md"
           - MySQL: "how-it-works/database/mysql.md"
           - PostgresSQL: "how-it-works/database/postgres.md"
        - Storage: "how-it-works/storage/storage.md"
        - CDN: "how-it-works/cdn/cdn.md"
        - CI/CD: "how-it-works/ci-cd/ci-cd.md"
        - Tools: "how-it-works/tools/tools.md"
        - Monitoring:
          - Monitoring: "how-it-works/monitoring/monitoring.md"
          - Metrics: "how-it-works/monitoring/metrics.md"
          - Logs: "how-it-works/monitoring/logs.md"
          - Tracing: "how-it-works/monitoring/tracing.md"
        - Secrets: "how-it-works/secrets/secrets.md"
        - Reliability:
          - Disaster Recovery: "how-it-works/reliability/dr.md"
          - Health Checks: "how-it-works/reliability/health-checks.md"
          - Backups: "how-it-works/reliability/backups.md"
        - Costs: "how-it-works/costs/costs.md"
        - Read More: "how-it-works/read-more.md"
  - User guide:
      - Configuration:
          - Configs: "user-guide/configuration/configs.md"
          - Basic usage: "user-guide/index.md"
  - Examples:
      - Introduction: "examples/index.md"
      - Prerequisites: "examples/PREREQUISITES.md"
      - AWS:
          - Organization: "examples/organization.md"
          - K8s Kops: "examples/k8s-kops.md"
