---
- name: Check if vault is initialized
  environment:
    VAULT_ADDR: '{{ _vault_address }}'
  shell: 'vault status -format=json'
  ignore_errors: yes
  become: no
  register: vault_status_result

- name: Parse output as JSON
  set_fact:
    '{{ _vault_status_output_variable }}': '{{ vault_status_result.stdout | from_json }}'
