---
#
# Vault Config directory
#
- name: Create vault config directory
  file:
    path: '{{ _vault_conf_dir }}'
    state: directory

- name: Copy vault config
  template:
    src: config.hcl
    dest: '{{ _vault_conf_dir }}'

#
# Vault File Backend directory
#
- name: Create vault file backend directory
  file:
    path: '{{ _vault_file_backend_dir }}'
    state: directory

#
# Set up a SystemD service
#
- name: Check if vault systemd system directory exists
  stat: path='{{ _vault_systemd_service_dir }}'
  register: vault_service_dir

- name: Create systemd system directory if need be
  when: vault_service_dir.stat.exists == False
  file:
    path: '{{ _vault_systemd_service_dir }}'
    state: directory

- name: Check if vault systemd service exists
  stat: path='{{ _vault_systemd_service_dir }}/vault.service'
  register: vault_service_file

- name: Create vault systemd service if missing
  when: vault_service_file.stat.exists == False
  template:
    src: vault.service
    dest: '{{ _vault_systemd_service_dir }}/vault.service'
    mode: 0644

- name: Ensure vault service is started and enabled at boot
  service:
    name: vault
    state: started
    enabled: yes