---
- hostname:
    name: "{{ server_hostname }}"

- name: add hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: '127.0.0.1 localhost {{ server_hostname }}'
    state: present

- name: Install prerequisites
  apt: pkg="{{ item }}" update_cache=yes cache_valid_time=86400 state=present
  with_items:
    - python3-pip
  when: ansible_os_family == "Debian"
  tags: packages

- name: Python3 pip upgrade
  command: pip3 install --upgrade pip==19.0.3