---
- name: Enable KV version 2
  when: _vault_config_enable_kv_v2
  environment:
    VAULT_ADDR: '{{ _vault_address }}'
    VAULT_TOKEN: '{{ _vault_token }}'
  # Note we are actually upgrading existing kv v1 under path 'secret'
  command: 'vault kv enable-versioning secret/'
  become: no

- name: Enable audit to file
  when: _vault_config_enable_audit
  environment:
    VAULT_ADDR: '{{ _vault_address }}'
    VAULT_TOKEN: '{{ _vault_token }}'
  command: 'vault audit enable file file_path={{ _vault_config_enable_audit_file_path }}'
  become: no
