---
#
# Initialize vault, store root token and unseal
#
- name: Initialize Vault
  environment:
    VAULT_ADDR: '{{ _vault_address }}'
  command: 'vault operator init -format=json'
  become: no
  register: vault_init_result

- name: Parse output as JSON
  set_fact:
    vault_init_output: "{{ vault_init_result.stdout | from_json }}"

- debug: msg="{{ vault_init_output }}"

- name: Store token and unseal keys
  set_fact:
    '{{ _vault_root_token_output_variable }}': '{{ vault_init_output.root_token }}'
    '{{ _vault_unseal_keys_output_variable }}': '{{ vault_init_output.unseal_keys_b64 }}'

- name: Clear previous output
  set_fact:
    vault_init_output: ''
