---
- name: Check Github Auth
  environment:
    VAULT_ADDR: '{{ _vault_address }}'
    VAULT_TOKEN: '{{ _vault_token }}'
  shell: 'vault auth list | grep github | wc -l'
  become: no
  register: vault_auth_list_result

- name: Enable Github Auth
  when: vault_auth_list_result.stdout == '0'
  environment:
    VAULT_ADDR: '{{ _vault_address }}'
    VAULT_TOKEN: '{{ _vault_token }}'
  command: 'vault auth enable github'
  become: no
  register: vault_auth_enable_result

- name: Configure Github Auth
  environment:
    VAULT_ADDR: '{{ _vault_address }}'
    VAULT_TOKEN: '{{ _vault_token }}'
  command: 'vault write auth/github/config organization={{ _github_organization }}'
  become: no
  register: vault_write_auth_org_result

- name: Configure Github Teams/Policies
  environment:
    VAULT_ADDR: '{{ _vault_address }}'
    VAULT_TOKEN: '{{ _vault_token }}'
  command: 'vault write auth/github/map/teams/{{ item.team }} value={{ item.policies | join(",") }}'
  become: no
  register: vault_write_auth_teams_result
  loop: '{{ _github_teams_policies }}'
