---
# @param        github_organization
# @description  Name of the organization on Github
#
_github_organization: ''

# @param github_teams_policies
# @description
#   A list of team-policy entries such as the following:
#       - team: team_name_1
#         policies:
#           - policy_name_1
#
_github_teams_policies: []

# Vault Address
_vault_address: http://127.0.0.1:8200

# Vault Token
_vault_token: ''