apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: {{ .cluster_name.value }}
spec:
  api:
    loadBalancer:
      type: Internal
      additionalSecurityGroups: [ {{ .cluster_api_elb_extra_security_group.value }} ]
  authentication:
    aws: {}
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    Environment: devstg
    Provisioner: kops
    Service: kubernetes
    Backup: "True"
  cloudProvider: aws
  configBase: s3://{{ .kops_s3_bucket.value }}/{{ .cluster_name.value }}
  dnsZone: {{ .hosted_zone_id.value }}
  #
  # Define etcd members (as many as masters were defined)
  #
  etcdClusters:
  - etcdMembers:
  {{ range $i, $az := .cluster_master_azs.value }}
    - instanceGroup: master-{{ . }}
      name: {{ . | replace $.region.value "" }}
      encryptedVolume: true
  {{ end }}
    name: main
    version: 3.3.10
  - etcdMembers:
  {{ range $i, $az := .cluster_master_azs.value }}
    - instanceGroup: master-{{ . }}
      name: {{ . | replace $.region.value "" }}
      encryptedVolume: true
  {{ end }}
    name: events
    version: 3.3.10
  iam:
    allowContainerRegistry: true
    legacy: true
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - {{ .shared_vpc_cidr_block.value }}
  kubernetesVersion: {{ .cluster_version.value }}
  masterInternalName: api.internal.{{ .cluster_name.value }}
  masterPublicName: api.{{ .cluster_name.value }}
  networkCIDR: {{ .vpc_cidr_block.value }}
  networkID: {{ .vpc_id.value }}
  networking:
    calico:
      majorVersion: v3
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - {{ .shared_vpc_cidr_block.value }}
  subnets:
  #
  # Define all public (utility) subnets that should be available for the cluster
  #
  {{ range $az, $id := .public_subnet_ids.value }}
  - id: {{ $id }}
    name: utility-{{ $az }}
    type: Utility
    zone: {{ $az }}
  {{ end }}
  #
  # Define all private subnets that should be available for the cluster
  #
  {{ range $az, $id := .private_subnet_ids.value }}
  - id: {{ $id }}
    name: {{ $az }}
    type: Private
    zone: {{ $az }}
    egress: {{ index $.nat_gateway_ids.value $az }}
  {{ end }}
  #
  # Cluster Topology
  #
  topology:
    dns:
      type: Private
    masters: private
    nodes: private
---

#
# Create as many master nodes as were defined
#
{{ range .cluster_master_azs.value }}
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{ $.cluster_name.value }}
  name: master-{{ . }}
spec:
  image: {{ $.kops_ami_id.value }}
  kubernetesVersion: {{ $.cluster_version.value }}
  machineType: m5.large
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - {{ . }}
---
  {{ end }}

#
# Instance group (workers) are defined below, starting with a single group
#
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{ .cluster_name.value }}
  name: nodes
spec:
  {{ if .node_cloud_labels.value }}
  cloudLabels:
    {{ range $name, $value := .node_cloud_labels.value }}
      {{ $name }}: "{{ $value }}"
    {{ end }}
  {{ end }}
  image: {{ $.kops_ami_id.value }}
  kubernetesVersion: {{ .cluster_version.value }}
  machineType: t2.medium
  maxSize: 3
  minSize: 3
  role: Node
  subnets:
  {{ range .availability_zones.value }}
  - {{ . }}
  {{ end }}
