---
#======================================================================#
# USERS to ADD w/ home dir (Comment only when removing users           #
#======================================================================#
- user:
    name: "{{item}}"
    comment: "{{item}}"
    createhome: yes
    home: /home/{{item}}
    groups: sudo
    state: present
  with_items:
    - "{{username1}}"
    - "{{username2}}"
    - "{{username3}}"
#    - "{{username4}}"


#======================================================================#
# USERS to REMOVE w/ home dir (Uncomment only when removing users)     #
#======================================================================#
- name: USERS to REMOVE w/ home dir
  user:
    name: "{{item}}"
    comment: "{{item}}"
    createhome: yes
    home: /home/{{item}}
    groups: sudo
    state: absent
    remove: yes
  with_items:
#    - "{{username1}}"
#    - "{{username2}}"
#    - "{{username3}}"
    - "{{username4}}"
  when:
    - openvpn_delete_users == True
  tags: delete_user


#======================================================================#
# USERS ADD ssh authorized key                                         #
#======================================================================#
- name: Set authorized key for "{{item}}"
  authorized_key:
    user: "{{item}}"
    state: present
    key: "{{ lookup('file', 'files/id_rsa_{{ item }}.pub') }}"
  with_items:
    - "{{username1}}"
    - "{{username2}}"
    - "{{username3}}"
#    - "{{username4}}"


#======================================================================#
# USERS allow sudo without password input                              #
#======================================================================#
- lineinfile: "dest=/etc/sudoers state=present regexp='^%sudo' line='%sudo ALL=(ALL) NOPASSWD: ALL'"